name: Student Sign-up
description: Sign-up Sheet for collaboration on course repository
title: "[SIGN-UP] <Full Name>, <SIS ID>"
labels: ["sign-up"]
body:

- type: dropdown
  id: semester
  attributes: 
    label: Semester
    options: 
      - 24Fall
      - 25Spring
      - 25Fall

- type: input
  id: full_name
  attributes:
    label: Full Name
  validations: 
    required: true

- type: input
  id: sis_id
  attributes:
    label: SIS ID
  validations: 
    required: true

- type: input 
  id: github_email
  attributes:
    label: Email address you've used to sign up for GitHub. 
  validations: 
    required: true
    
- type: input 
  id: github_handle
  attributes: 
    label: GitHub username/handle
  validations: 
    required: true
