name: Student Sign-up
description: Sign-up Sheet for collaboration on course repository
title: "[SIGN-UP] <Full Name>, <SIS ID>"
labels: ["sign-up"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: full_name
  attributes:
    label: Your Full Name

- type: input
  id: sis_id
  attributes:
    label: Provide your SIS ID

- type: input 
  id: github_email
  attributes:
    label: Email address you've used to sign up for GitHub. 

- type: input 
  id: github_handle
  attributes: 
    label: Your GitHub username/handle

