name: Student Sign-up
description: Sign-up Sheet for collaboration on course repository
title: "[SIGN-UP] <Full Name>, <SIS ID>"
labels: ["sign-up"]
body:
- type: input
  id: full_name
  attributes:
    label: Your Full Name
    options:
      required: true
